name: test

on: [push, pull_request]

jobs:
  test-windows:
    name: windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: |
          iex (irm install.sinjs.com)
          sin test -d
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-other:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: |
          source <(curl -fsSL install.sinjs.com)
          sin test -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
