name: test

on: [push, pull_request]

jobs:
  test-windows:
    name: windows-latest w. Node v${{ matrix.node }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: |
          iex (irm install.sinjs.com)
          echo $env:path
          sin test
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-other:
    name: ${{ matrix.os }} w. Node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -fsSL install.sinjs.com > installer.sh
          cat installer.sh
          source installer.sh
          echo $PATH
          sin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
