name: test

on: [push, pull_request]

jobs:
  test-windows:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          iex (irm install.sinjs.com)
          sin test -d
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-macos:
    name: macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          source <(curl -fsSL install.sinjs.com)
          sin test -d
        shell: zsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-linux:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          source <(curl -fsSL install.sinjs.com)
          sin test -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
